using static Model.OneDSolver;

namespace CLI;

public class OneDScenarios
{
    public static Scenario Big = new Scenario([
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
        new Product(10),
    ]);
}